version: '3'
services:
 
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: 123
 
  server:
    image: capstone-server:latest
    container_name: server
    restart: always
    ports:
      - "7000:7000"
